package com.demo.matchers;

import com.demo.model.ErrorResponse;
import org.assertj.core.api.AbstractAssert;
import org.assertj.core.util.Objects;

/**
 * {@link ErrorResponse} specific assertions - Generated by CustomAssertionGenerator.
 */
public class ErrorResponseAssert extends AbstractAssert<ErrorResponseAssert, ErrorResponse> {

    public ErrorResponseAssert(ErrorResponse actual) {
        super(actual, ErrorResponseAssert.class);
    }

    public static ErrorResponseAssert assertThat(ErrorResponse actual) {
        return new ErrorResponseAssert(actual);
    }

    public ErrorResponseAssert hasCod(Integer cod) {
        isNotNull();
        String assertjErrorMessage = "\nExpecting cod of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
        Integer actualCod = actual.getCod();
        if (!Objects.areEqual(actualCod, cod)) {
            failWithMessage(assertjErrorMessage, actual, cod, actualCod);
        }
        return this;
    }

    public ErrorResponseAssert hasMessage(String message) {
        isNotNull();
        String assertjErrorMessage = "\nExpecting message of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
        String actualMessage = actual.getMessage();
        if (!Objects.areEqual(actualMessage, message)) {
            failWithMessage(assertjErrorMessage, actual, message, actualMessage);
        }
        return this;
    }
}
